{
 "title": "Consul",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(consul_raft_applied_index, environment)"
    }
   },
   { "name": "quantile", "label": "Quantile", "query": "0.5,0.9,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Current Raft Index",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consul_raft_applied_index{environment=\"$env\"}"
    }
   ]
  },
  {
   "title": "Raft Leader Last Contact",
   "type": "stat",
   "description": "Time since the leader last contacted all follower nodes. ",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consul_raft_leader_lastContact{application=\"consul\", environment=\"$env\", quantile=\"$quantile\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 16, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum by (host) (rate(host_cpu_seconds_total{mode='idle',application=\"consul\", environment=\"$env\"}[5m])) / (count by (host) (host_cpu_seconds_total{mode='idle', application=\"consul\", environment=\"$env\"})))",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (host) (\n  host_memory_total_bytes{job=\"integrations/linux_host\", application=\"consul\", environment=\"$env\"}\n-\n  host_memory_free_bytes{job=\"integrations/linux_host\", application=\"consul\", environment=\"$env\"}\n-\n  host_memory_buffers_bytes{job=\"integrations/linux_host\", application=\"consul\", environment=\"$env\"}\n-\n  host_memory_cached_bytes{job=\"integrations/linux_host\", application=\"consul\", environment=\"$env\"}\n) / avg by (host) (host_memory_total_bytes{job=\"integrations/linux_host\", application=\"consul\", environment=\"$env\"})\n",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Host Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "host_uptime{environment=\"$env\", application=\"consul\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Golang Heap Objects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_runtime_heap_objects{environment=\"$env\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Transaction Performance",
   "type": "timeseries",
   "description": "* Measures the time it takes to complete an update to the KV store.\n* Measures the time spent applying a transaction operation. \n* Measures the time it takes to commit a new entry to the Raft log on the leader.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "consul_kvs_apply{environment=\"$env\",quantile=\"$quantile\"}",
     "legendFormat": "Update KV Store Time - {{ environment }} - {{ quantile }}"
    },
    {
     "expr": "consul_txn_apply{environment=\"$env\",quantile=\"$quantile\"}",
     "legendFormat": "Apply Transaction Time - {{ environment }} - {{ quantile }}"
    },
    {
     "expr": "consul_raft_commitTime{environment=\"$env\",quantile=\"$quantile\"}",
     "legendFormat": "Raft Commit Time - {{ environment }} - {{ quantile }}"
    }
   ]
  }
 ]
}