{
 "title": "Application Performance (All Heroku Apps)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "application",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(application) (quantile_over_time(0.95, {service=\"heroku\", application=\"$application\"} | json | line_format `{{.message}}` | logfmt | unwrap duration(service_extracted) | __error__=`` [$__interval]))"
    }
   ]
  },
  {
   "title": "HTTP Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({service=\"heroku\", application=\"$application\"} | json | line_format `{{.message}}` | logfmt | __error__=\"\" | proc_id = `router` [$__interval]))",
     "legendFormat": "{{.status}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(application) (count_over_time({service=\"heroku\", application=\"$application\"} | json |= `Request timeout` [$__interval]))",
     "legendFormat": "timeouts"
    },
    {
     "expr": "sum by(application) (count_over_time({service=\"heroku\", application=\"$application\"} |= `a process holding a robust mutex died. recovering...` [$__interval]))",
     "legendFormat": "deadlocks"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(application) (count_over_time({service=\"heroku\", application=\"$application\"} | json | line_format `{{.message}}` | logfmt | __error__=`` | proc_id = `router` [$__interval]))",
     "legendFormat": "# of Requests"
    }
   ]
  },
  {
   "title": "503 Returns by path prefix - Bucketed into 10 minute Intervals",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (path) (count_over_time({service=\"heroku\", application=\"$application\"} | json | line_format `{{.message}}` | logfmt | __error__=`` | proc_id = `router` | status = `503` | line_format `{{.path}}` | pattern `/<path>/<_>` | line_format `{{.path}}`[$__interval]))",
     "legendFormat": "{{.status}}"
    }
   ]
  },
  {
   "title": "404 Returns by path prefix - Bucketed into 10 minute Intervals",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (path) (count_over_time({service=\"heroku\", application=\"$application\"} | json | line_format `{{.message}}` | logfmt | __error__=`` | proc_id = `router` | status = `404` | line_format `{{.path}}` | pattern `/<path>/<_>` | line_format `{{.path}}`[$__interval]))",
     "legendFormat": "{{.status}}"
    }
   ]
  }
 ]
}