{
 "title": "Vault",
 "tags": [
  "managed",
  "vault",
  "performance"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Seal Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(1 + vault_core_unsealed{})" }
   ]
  },
  {
   "title": "Secrets",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "avg without(instance, host, environment, service, application, org_unit) (vault_secret_kv_count)",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Lease Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(vault_expire_num_leases)" }
   ]
  },
  {
   "title": "Host Uptime",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "host_uptime{application=\"vault\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Request Handle Duration - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vault_core_handle_request{quantile=~\"0.9+\"}",
     "legendFormat": "Request Handle Duration - {{ quantile }} percentile"
    }
   ]
  }
 ]
}