{
 "title": "Logs By Environment",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "label_values({}, environment)" },
   {
    "name": "application",
    "query": "label_values({environment=\"$environment\"}, application)"
   },
   {
    "name": "service",
    "query": "label_values({environment=\"$environment\"}, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "$environment",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "repeat": "environment",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"$environment\"}[5m])/1024/1024)"
    }
   ]
  },
  {
   "title": "Usage by Environment",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({environment=\"$environment\"}[1d]))/1e6"
    }
   ]
  },
  {
   "title": "Usage by Environment > Application",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "repeat": "application",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({environment=\"$environment\",application=\"$application\"}[1d]))/1e6"
    }
   ]
  },
  {
   "title": "Log Usage By Environment",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "repeat": "application",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"$environment\",application=\"$application\"}[5m])/1024/1024)",
     "legendFormat": "$application"
    }
   ]
  },
  {
   "title": "Log Usage By Environment",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "repeat": "application",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"$environment\",application=\"$application\"}[5m])/1024/1024)",
     "legendFormat": "$application"
    }
   ]
  },
  {
   "title": "Log Usage By Environment",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"mitx-ci\", application=\"consul\"}[5m])/1024/1024)",
     "legendFormat": "mitx-ci"
    },
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"mitx-staging-ci\"}[5m])/1024/1024)",
     "legendFormat": "mitx-staging-ci"
    },
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"mitxonline-ci\"}[5m])/1024/1024)",
     "legendFormat": "mitxonline-ci"
    },
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"operations-ci\"}[5m])/1024/1024)",
     "legendFormat": "operations-ci"
    },
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"xpro-ci\"}[5m])/1024/1024)",
     "legendFormat": "xpro-ci"
    }
   ]
  },
  {
   "title": "Log Usage By Environment",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"mitx-ci\"}[5m])/1024/1024)",
     "legendFormat": "mitx-ci"
    },
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"mitx-staging-ci\"}[5m])/1024/1024)",
     "legendFormat": "mitx-staging-ci"
    },
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"mitxonline-ci\"}[5m])/1024/1024)",
     "legendFormat": "mitxonline-ci"
    },
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"operations-ci\"}[5m])/1024/1024)",
     "legendFormat": "operations-ci"
    },
    {
     "expr": "sum by(environment)(bytes_over_time({environment=\"xpro-ci\"}[5m])/1024/1024)",
     "legendFormat": "xpro-ci"
    }
   ]
  }
 ]
}