{
 "title": "xPro Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(application) (quantile_over_time(0.95, {service=\"heroku\", application=\"xpro\"} | json | line_format `{{.message}}` | logfmt | unwrap duration(service_extracted) | __error__=`` [5m]))"
    }
   ]
  },
  {
   "title": "HTTP Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({service=\"heroku\", application=\"xpro\"} | json | line_format `{{.message}}` | logfmt | proc_id = `router` [1h]))",
     "legendFormat": "{{.status}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(application) (count_over_time({service=\"heroku\", application=\"xpro\"} | json |= `Request timeout` [5m]))",
     "legendFormat": "timeouts"
    },
    {
     "expr": "sum by(application) (count_over_time({service=\"heroku\", application=\"xpro\"} |= `a process holding a robust mutex died. recovering...` [5m]))",
     "legendFormat": "deadlocks"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (application) (count_over_time({service=\"heroku\", application=\"xpro\"} | json | line_format `{{.message}}` | logfmt | proc_id = `router` [1h]))",
     "legendFormat": "# of Requests"
    }
   ]
  }
 ]
}