{
 "title": "Instance Metrics",
 "description": "A quickstart to setup Prometheus Node Exporter with preconfigured dashboards, alerting rules, and recording rules.",
 "tags": [
  "node",
  "host",
  "instance",
  "metrics",
  "managed"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(host_uptime{job=\"integrations/linux_host\"},environment)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(host_uptime{job=\"integrations/linux_host\", environment=~\"$environment\"},application)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(host_uptime{job=\"integrations/linux_host\", environment=~\"$environment\", application=~\"$application\"}, service)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(host_uptime{job=\"integrations/linux_host\", environment=~\"$environment\", application=~\"$application\", service=~\"$service\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  (1 - rate(host_cpu_seconds_total{job=\"integrations/linux_host\", mode=\"idle\", host=\"$instance\"}[$__interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( host_cpu_seconds_total{job=\"integrations/linux_host\", mode=\"idle\", host=\"$instance\"})\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "host_load1{job=\"integrations/linux_host\", host=\"$instance\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "host_load5{job=\"integrations/linux_host\", host=\"$instance\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "host_load15{job=\"integrations/linux_host\", host=\"$instance\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(host_cpu_seconds_total{job=\"integrations/linux_host\", host=\"$instance\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  host_memory_total_bytes{job=\"integrations/linux_host\", host=\"$instance\"}\n-\n  host_memory_free_bytes{job=\"integrations/linux_host\", host=\"$instance\"}\n-\n  host_memory_buffers_bytes{job=\"integrations/linux_host\", host=\"$instance\"}\n-\n  host_memory_cached_bytes{job=\"integrations/linux_host\", host=\"$instance\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "host_memory_buffers_bytes{job=\"integrations/linux_host\", host=\"$instance\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "host_memory_cached_bytes{job=\"integrations/linux_host\", host=\"$instance\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "host_memory_free_bytes{job=\"integrations/linux_host\", host=\"$instance\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Avg Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg(host_memory_available_bytes{job=\"integrations/linux_host\", host=\"$instance\"}) / avg(host_memory_total_bytes{job=\"integrations/linux_host\", host=\"$instance\"}) * 100)\n"
    }
   ]
  },
  {
   "title": "Network Bytes Received ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(host_network_receive_bytes_total{job=\"integrations/linux_host\", host=\"$instance\", device!=\"lo\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(host_disk_read_bytes_total{job=\"integrations/linux_host\", host=\"$instance\", device=~\"nvme.*\"}[$__interval])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "rate(host_disk_written_bytes_total{job=\"integrations/linux_host\", host=\"$instance\", device=~\"nvme.*\"}[$__interval])",
     "legendFormat": "{{device}} - written"
    }
   ]
  },
  {
   "title": "Network Bytes Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(host_network_transmit_bytes_total{job=\"integrations/linux_host\", host=\"$instance\", device!=\"lo\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Usage - Percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "host_filesystem_used_ratio{job=\"integrations/linux_host\", host=\"$instance\", filesystem!=\"\", device=~\"/dev.*\"}\n\n",
     "legendFormat": "{{device}} - used %"
    }
   ]
  },
  {
   "title": "Disk Space Usage - Raw",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "host_filesystem_used_bytes{job=\"integrations/linux_host\", host=\"$instance\", filesystem!=\"\", device=~\"/dev.*\"}\n\n",
     "legendFormat": "{{device}} - used"
    },
    {
     "expr": "host_filesystem_free_bytes{job=\"integrations/linux_host\", host=\"$instance\", filesystem!=\"\", device=~\"/dev.*\"}\n\n",
     "legendFormat": "{{device}} - available"
    }
   ]
  }
 ]
}